import career1 from "../img/career/career-logo.jpg";

const CareerData = [
  {
    id: 1,
    companyName: "MocaStroot.Inc",
    jobTitle: "Sr. UI/UX Designer",
    location: "United States",
    date: "3rd June, 2024",
    img: career1,
    prise: "$25k - 150k/year",
    slug: "1",
  },
  {
    id: 2,
    companyName: "MocaStroot.Inc",
    jobTitle: "Sr.Backend Developer",
    location: "United States",
    date: "5th June, 2024",
    img: career1,
    prise: "$35k - 150k/year",
    slug: "2",
  },
  {
    id: 3,
    companyName: "MocaStroot.Inc",
    jobTitle: "Web Developer",
    location: "United States",
    date: "6th June, 2024",
    img: career1,
    prise: "$45k - 150k/year",
    slug: "3",
  },
  {
    id: 4,
    companyName: "MocaStroot.Inc",
    jobTitle: "Web Designer",
    location: "United States",
    date: "7th June, 2024",
    img: career1,
    prise: "$50k - 150k/year",
    slug: "4",
  },
  {
    id: 5,
    companyName: "MocaStroot.Inc",
    jobTitle: "UI/UX Designer",
    location: "United States",
    date: "8th June, 2024",
    img: career1,
    prise: "$55k - 150k/year",
    slug: "5",
  },
  {
    id: 6,
    companyName: "MocaStroot.Inc",
    jobTitle: "Full-Stack Developer",
    location: "United States",
    date: "9th June, 2024",
    img: career1,
    prise: "$45k - 350k/year",
    slug: "6",
  },
  {
    id: 7,
    companyName: "MocaStroot.Inc",
    jobTitle: "React Developer",
    location: "United States",
    date: "10th June, 2024",
    img: career1,
    prise: "$35k - 350k/year",
    slug: "7",
  },
  {
    id: 8,
    companyName: "MocaStroot.Inc",
    jobTitle: "Plugin Developer",
    location: "United States",
    date: "11th June, 2024",
    img: career1,
    prise: "$45k - 250k/year",
    slug: "8",
  },
  {
    id: 9,
    companyName: "MocaStroot.Inc",
    jobTitle: "Theme Developer",
    location: "United States",
    date: "12th June, 2024",
    img: career1,
    prise: "$35k - 250k/year",
    slug: "9",
  },
  {
    id: 10,
    companyName: "MocaStroot.Inc",
    jobTitle: "DevOps Engineer",
    location: "United States",
    date: "13th June, 2024",
    img: career1,
    prise: "$55k - 160k/year",
    slug: "10",
  },
  {
    id: 11,
    companyName: "MocaStroot.Inc",
    jobTitle: "System Administrator",
    location: "United States",
    date: "14th June, 2024",
    img: career1,
    prise: "$40k - 130k/year",
    slug: "11",
  },
  {
    id: 12,
    companyName: "MocaStroot.Inc",
    jobTitle: "Network Engineer",
    location: "United States",
    date: "15th June, 2024",
    img: career1,
    prise: "$45k - 140k/year",
    slug: "12",
  },
  {
    id: 13,
    companyName: "MocaStroot.Inc",
    jobTitle: "Mobile App Developer",
    location: "United States",
    date: "16th June, 2024",
    img: career1,
    prise: "$50k - 180k/year",
    slug: "13",
  },
  {
    id: 14,
    companyName: "MocaStroot.Inc",
    jobTitle: "Product Manager",
    location: "United States",
    date: "17th June, 2024",
    img: career1,
    prise: "$60k - 200k/year",
    slug: "14",
  },
  {
    id: 15,
    companyName: "MocaStroot.Inc",
    jobTitle: "QA Engineer",
    location: "United States",
    date: "18th June, 2024",
    img: career1,
    prise: "$40k - 120k/year",
    slug: "15",
  },
  {
    id: 16,
    companyName: "MocaStroot.Inc",
    jobTitle: "IT Support Specialist",
    location: "United States",
    date: "19th June, 2024",
    img: career1,
    prise: "$35k - 110k/year",
    slug: "16",
  },
  {
    id: 17,
    companyName: "MocaStroot.Inc",
    jobTitle: "Cloud Engineer",
    location: "United States",
    date: "20th June, 2024",
    img: career1,
    prise: "$60k - 180k/year",
    slug: "17",
  },
  {
    id: 18,
    companyName: "MocaStroot.Inc",
    jobTitle: "Security Analyst",
    location: "United States",
    date: "21st June, 2024",
    img: career1,
    prise: "$55k - 160k/year",
    slug: "18",
  },
  {
    id: 19,
    companyName: "MocaStroot.Inc",
    jobTitle: "Business Analyst",
    location: "United States",
    date: "22nd June, 2024",
    img: career1,
    prise: "$50k - 140k/year",
    slug: "19",
  },
  {
    id: 20,
    companyName: "MocaStroot.Inc",
    jobTitle: "Technical Writer",
    location: "United States",
    date: "23rd June, 2024",
    img: career1,
    prise: "$30k - 100k/year",
    slug: "20",
  },
  {
    id: 21,
    companyName: "MocaStroot.Inc",
    jobTitle: "Graphic Designer",
    location: "United States",
    date: "24th June, 2024",
    img: career1,
    prise: "$35k - 90k/year",
    slug: "21",
  },
  {
    id: 22,
    companyName: "MocaStroot.Inc",
    jobTitle: "Content Strategist",
    location: "United States",
    date: "25th June, 2024",
    img: career1,
    prise: "$40k - 120k/year",
    slug: "22",
  },
  {
    id: 23,
    companyName: "MocaStroot.Inc",
    jobTitle: "SEO Specialist",
    location: "United States",
    date: "26th June, 2024",
    img: career1,
    prise: "$35k - 100k/year",
    slug: "23",
  },
  {
    id: 24,
    companyName: "MocaStroot.Inc",
    jobTitle: "Digital Marketing Manager",
    location: "United States",
    date: "27th June, 2024",
    img: career1,
    prise: "$50k - 140k/year",
    slug: "24",
  },
];

export default CareerData;
